# Generated by Django 5.1.2 on 2025-04-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readlistbook',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='readlistbook',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
