# Generated by Django 5.1.2 on 2025-02-25 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readlist',
            name='books',
            field=models.ManyToManyField(related_name='readlists', through='api.ReadlistBook', to='api.book'),
        ),
        migrations.AlterField(
            model_name='readlistbook',
            name='readlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readlist_books', to='api.readlist'),
        ),
    ]
