# Generated by Django 5.1.2 on 2025-04-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_readlistbook_options_readlistbook_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookstatus',
            name='finished_points_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userbookstatus',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('READING', 'Currently Reading'), ('FINISHED', 'Finished'), ('WANT_TO_READ', 'Want to Read')], default='NOT_STARTED', max_length=15),
        ),
    ]
