# Generated by Django 5.1.2 on 2024-12-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authorName',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='coverIMG',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publishedDate',
        ),
        migrations.AddField(
            model_name='book',
            name='google_books_id',
            field=models.CharField(default='default_id', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn10',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn13',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
