# Generated by Django 5.1.2 on 2025-02-26 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('api', '0007_userfollow'),
    ]

    operations = [
    ]