# Generated by Django 5.1.2 on 2025-03-01 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20250226_1604'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='readlist',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_readlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
